#!/usr/bin/env python
"""Generate the Overleaf-ready Office Products ablation results table."""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_ROOT = Path("/gpfs/work5/0/prjs2120/groups/group_06/checkpoints/SIDReasoner")
OUTPUT = REPO_ROOT / "experiments" / "OFFICE_PRODUCTS_ABLATION_RESULTS.tex"
METRICS = ("HR@5", "NDCG@5", "HR@10", "NDCG@10")


def load(path: Path) -> dict:
    return json.loads(path.read_text())


def validate(metrics: dict, source: Path) -> None:
    if metrics.get("total") != 4866 or metrics.get("evaluated") != 4866 or metrics.get("errors") != 0:
        raise ValueError(f"Unexpected incomplete result in {source}")
    missing = [metric for metric in METRICS if metric not in metrics]
    if missing:
        raise ValueError(f"Missing metrics {missing} in {source}")


def record(label: str, split: str, reasoning: str, metrics: dict, source: Path) -> tuple:
    validate(metrics, source)
    return (label, split, reasoning, *(float(metrics[metric]) for metric in METRICS))


def block(rows: list[tuple], title: str) -> list[str]:
    lines = [rf"\multicolumn{{8}}{{l}}{{\textit{{{title}}}}} \\", r"\addlinespace[2pt]"]
    for position, row in enumerate(rows):
        label, split, reasoning, *values = row
        dataset = rf"\multirow{{{len(rows)}}}{{*}}{{Office Products}}" if position == 0 else ""
        numbers = " & ".join(f"{value:.4f}" for value in values)
        lines.append(f"{dataset} & {split} & {label} & {reasoning} & {numbers} " + r"\\")
    return lines


def main() -> None:
    ablation_root = ARTIFACT_ROOT / "office_products_ablation_20260612"
    ablation_report_path = REPO_ROOT / "experiments" / "office_products_ablation_20260612" / "evaluation_report.json"
    ablation_report = load(ablation_report_path)
    stage2_source = ablation_root / "stage2_baseline" / "evaluation" / "common.metrics.json"
    initial_rows = [
        record("Stage 2 reference (constrained)", "Validation", "Off", load(stage2_source), stage2_source),
    ]
    labels = {
        "control": "Control (constrained rollouts)",
        "no_validity": "No validity bonus",
        "no_constrained": "No rollout constraints (constrained eval.)",
        "exact_only": "Exact-only reward",
        "lora_no_validity": "LoRA: no validity bonus",
        "lora_no_constrained": "LoRA: no rollout constraints (constrained eval.)",
    }
    for key, label in labels.items():
        initial_rows.append(record(label, "Validation", "Off", ablation_report[key]["metrics"], ablation_report_path))

    native_paths = {
        "No rollout constraints (native unconstrained eval.)": ablation_root
        / "no_constrained"
        / "step_500"
        / "evaluation"
        / "native.metrics.json",
        "LoRA: no rollout constraints (native unconstrained eval.)": ablation_root
        / "lora_no_constrained"
        / "step_200"
        / "evaluation"
        / "native.metrics.json",
    }
    for label, source in native_paths.items():
        initial_rows.append(record(label, "Validation", "Off", load(source), source))

    adaptive_root = ARTIFACT_ROOT / "adaptive_reasoning_20260613"
    validation_rows = []
    for model_key, label in (
        ("paper_stage3", "Reproduced Stage 3"),
        ("lora_no_constrained", "LoRA: no rollout constraints"),
    ):
        for filename, reasoning in (("direct.metrics.json", "Off"), ("generated_s1.metrics.json", "On")):
            source = adaptive_root / model_key / "validation" / "validation" / filename
            validation_rows.append(record(label, "Validation", reasoning, load(source), source))

    final_root = ARTIFACT_ROOT / "final_office_test_20260613"
    test_rows = []
    for model_key, label in (
        ("paper_stage3", "Reproduced Stage 3"),
        ("lora_no_constrained", "LoRA: no rollout constraints"),
    ):
        for mode, reasoning in (("direct", "Off"), ("generated", "On")):
            source = final_root / model_key / mode / "metrics.json"
            test_rows.append(record(label, "Test", reasoning, load(source), source))

    lines = [
        "% Requires: \\usepackage{booktabs,multirow}",
        "% Generated by scripts/generate_office_ablation_latex_table.py; do not edit values by hand.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Office Products ranking results. ``On'' generates a reasoning trace before constrained SID ranking; ``Off'' uses an empty reasoning block and ranks SIDs directly. Only ranking metrics are shown.}",
        r"\label{tab:office-products-ablations}",
        r"\small",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{lllccccc}",
        r"\toprule",
        r"Dataset & Split & Ablation / model & Reasoning & HR@5 & NDCG@5 & HR@10 & NDCG@10 \\",
        r"\midrule",
        *block(initial_rows, "Exploratory reward/rollout ablations; direct SID ranking"),
        r"\midrule",
        *block(validation_rows, "Fixed inference-mode comparison; full validation"),
        r"\midrule",
        *block(test_rows, "Frozen comparison; official test split"),
        r"\bottomrule",
        r"\end{tabular}",
        r"\begin{minipage}{0.98\textwidth}",
        r"\vspace{2pt}\footnotesize",
        r"\textit{Notes.} Each row evaluates 4,866 examples. All non-native rows use constrained beam-10 SID decoding. The two rows labelled ``native unconstrained'' use unconstrained beam-10 decoding and are retained because they are part of the original ablation study. The first validation block and the fixed inference-mode validation block use different evaluators, so rows with the same model name should only be compared within their labelled block. The author-released final checkpoint is excluded: its public SID index is incompatible with its released tokenizer, making its scores non-comparable.",
        r"\end{minipage}",
        r"\end{table*}",
        "",
    ]
    OUTPUT.write_text("\n".join(lines))
    print(OUTPUT)


if __name__ == "__main__":
    main()
